name: Ruff Format Check

on:
  push:
  pull_request:

jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Ruff formatting
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format --check --diff"
          src: "."
